package br.com.bluepersistence.model;

enum INTEGER {
	INT, INTEGER, TINYINT , SMALLINT, MEDIUMINT, BIGINT, UNSIGNED, BIG , INT2, INT8;
}

enum TEXT {
	CHAR, VARCHAR, VARYINGCHARACTER255, NCHAR55, NATIVECHARACTER70, NVARCHAR100, TEXT, CLOB;
}

enum NONE {
	BLOB;
}

enum REAL {
	REAL, DOUBLE, DOUBLEPRECISION, FLOAT;
}

enum NUMERIC {
	NUMERIC, DECIMAL, BOOLEAN, DATE, DATETIME; 
}

enum CHAVEESTRANGEIRA {
	FK; 
}


